version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PASSWORD: ""
      DB_NAME: "HelloWorld"

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
